stages:
- stage: Requirements
  jobs:
  - job: InstallRequirements
    steps:
    - script: echo Installing Requirements!

- stage: Build
  jobs:
  - job: BuildOnWindows
    steps:
    - script: echo Building on Windows!
  - job: BuildOnLinux
    steps:
    - script: echo Building on Linux!

- stage: Test
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!