# https://docs.microsoft.com/azure/devops/pipelines/languages/python

jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip3 install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      make
      ls -lah
    displayName: 'Build binary'

- job: 'Windows'
  pool:
    vmImage: 'vs2017-win2016'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip3 install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      make
      dir
    displayName: 'Build binary'

- job: 'Apple'
  pool:
    vmImage: 'macOS-10.13'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'

  - script: pip3 install -r requirements.txt
    displayName: 'Install requirements'

  - script: |
      make
      ls -lah
    displayName: 'Build binary'
