jobs:

- job: 'Linux'
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.6'
  - script: |
      python3 -m pip install --upgrade pip
      python3 -m pip install -r requirements.txt
  - script: |
      pylint -j0 src/*.py
  - script: |
      pytest --junitxml=results.xml
  - task: PublishTestResults@2
    inputs:
      testResultsFiles: 'results.xml'
      testRunTitle: "$(Agent.OS) - $(Build.BuildNumber)[$(Agent.JobName)] - Python $(python.version)"