stages:
- template: stages/cross-platform.yml
  parameters:
    name: Windows
    platform: windows-latest

- template: stages/cross-platform.yml
  parameters:
    name: MacOS
    platform: macOS-latest

- template: stages/cross-platform.yml
  parameters:
    name: Linux
    platform: ubuntu-latest