stages:
- template: stages/static_checks.yml

- template: stages/cross-platform.yml
  parameters:
    name: Windows
    platform: vs2017-win2016

- template: stages/cross-platform.yml
  parameters:
    name: MacOS
    platform: macos-10.13

- template: stages/cross-platform.yml
  parameters:
    name: Linux
    platform: ubuntu-16.04