# https://docs.microsoft.com/azure/devops/pipelines/languages/python
      
jobs:
- job: dependencies
  displayName: Install dependencies
  steps:
  - script: pip3 install -r requirements.txt

- job: binary
  strategy:
    matrix:
      linux:
        imageName: "ubuntu-16.04"
        binary: PoolCalendar
      mac:
        imageName: "macos-10.13"
        binary: PoolCalendar
      windows:
        imageName: "vs2017-win2016"
        binary: PoolCalendar.exe
    maxParallel: 3
  pool:
    vmImage: $(imageName)
  displayName: Build Binary
  dependsOn: dependencies
  steps:
  - script: make

- job: testing
  strategy:
    matrix:
      linux:
        imageName: "ubuntu-16.04"
        binary: PoolCalendar
      mac:
        imageName: "macos-10.13"
        binary: PoolCalendar
      windows:
        imageName: "vs2017-win2016"
        binary: PoolCalendar.exe
    maxParallel: 3
  pool:
    vmImage: $(imageName)
  dependsOn: binary
  displayName: Test run Binary
  steps:
  - script: ./$(binary)