parameters:
  name: ''
  platform: ''

jobs:
- job: BuildOn${{ parameters.name }}
  pool:
    vmImage: ${{ parameters.platform }}
  steps:
  - task: UsePythonVersion@0
    displayName: Set Python version to 3.7
    inputs:
      versionSpec: '3.7'
  - bash: pip3 install -r requirements.txt
    displayName: Install Requirements
  - bash: make PLATFORM=${{ parameters.name }}
    displayName: Make Binary
  - bash: ls -lah
    displayName: List output
  - task: CopyFiles@2
    displayName: Copy Files to Staging
    inputs:
      contents: PoolCalendar_${{ parameters.name }}*
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    displayName: Publish Artifacts
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: PoolCalendar_${{ parameters.name }}
  - task: GithubRelease@0
    displayName: GitHub Release ${{ parameters.name }}
    inputs:
      action: edit
      gitHubConnection: Azure Pipeline
      repositoryName: $(Build.Repository.Name)
      tagSource: auto
      tag: PoolCalendar_${{ parameters.name }}$(Build.BuildNumber)
      title: Release_PoolCalendar_${{ parameters.name }}_$(Build.BuildNumber)
      assets: $(Build.ArtifactStagingDirectory)/PoolCalendar_${{ parameters.name }}